AWSTemplateFormatVersion: 2010-09-09
Description: >-
  schedule-line-reminder
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  CalendarEventsNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Description: Googleカレンダーの1週間分の予定を通知するLambda関数
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Handler: calendar-events-handler.calendarEventsHandler
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            # 毎日21時に実行する
            Schedule: cron(0 12 * * ? *)
      MemorySize: 128
      Timeout: 100
      Layers:
        # AWS Systems Managerのパラメータストアから設定値を取得するためのLambda Layer
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSLambdaBasicExecutionRole
        # AWS Systems Managerのパラメータストアから設定値を取得するためのポリシー
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "kms:Decrypt"
                - "ssm:GetParameter"
                - "dynamodb:Scan"
              Resource:
                [
                  Fn::Sub: "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm",
                  Fn::Sub: "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/schedule-line-reminder/*",
                  !GetAtt OAuthTokensTable.Arn,
                ]
        # UserCalendarsTableに対する権限
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:Query"
              Resource: !GetAtt UserCalendarsTable.Arn
      LoggingConfig:
        ApplicationLogLevel: DEBUG
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/calendar-events-handler.ts
        Banner:
          # モジュールの解決エラーを解決するために、esbuildのバナーにNode.jsのrequireを追加する
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
  WebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: LINEからのWebhookを処理するLambda関数
      Runtime: nodejs22.x
      Handler: line-webhook-handler.handler
      Architectures:
        - x86_64
      Events:
        LineWebhook:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post
      Timeout: 10
      LoggingConfig:
        ApplicationLogLevel: DEBUG
      Layers:
        # AWS Systems Managerのパラメータストアから設定値を取得するためのLambda Layer
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSLambdaBasicExecutionRole
        # AWS Systems Managerのパラメータストアから設定値を取得するためのポリシー
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "kms:Decrypt"
                - "ssm:GetParameter"
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
              Resource:
                [
                  Fn::Sub: "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm",
                  Fn::Sub: "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/schedule-line-reminder/*",
                  !GetAtt OAuthStateTable.Arn,
                  !GetAtt OAuthTokensTable.Arn,
                ]
            - Effect: Allow
              Action:
                - "dynamodb:GetItem"
              Resource: !GetAtt OAuthTokensTable.Arn
        # UserCalendarsTableに対する権限
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Query"
              Resource: !GetAtt UserCalendarsTable.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/line-webhook-handler.ts
        Banner:
          # モジュールの解決エラーを解決するために、esbuildのバナーにNode.jsのrequireを追加する
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
  OAuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Google OAuth2.0のコールバックを処理するLambda関数
      Runtime: nodejs22.x
      Handler: oauth-callback-handler.oauthCallbackHandler
      Architectures:
        - x86_64
      Events:
        OAuthCallback:
          Type: Api
          Properties:
            Path: /oauth/callback
            Method: get
      Timeout: 15
      LoggingConfig:
        ApplicationLogLevel: DEBUG
      Layers:
        # AWS Systems Managerのパラメータストアから設定値を取得するためのLambda Layer
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSLambdaBasicExecutionRole
        # AWS Systems Managerのパラメータストアから設定値を取得するためのポリシー
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "kms:Decrypt"
                - "ssm:GetParameter"
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:UpdateItem"
              Resource:
                [
                  Fn::Sub: "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm",
                  Fn::Sub: "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/schedule-line-reminder/*",
                  !GetAtt OAuthStateTable.Arn,
                  !GetAtt OAuthTokensTable.Arn,
                ]
        # UserCalendarsTableに対する権限
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Query"
              Resource: !GetAtt UserCalendarsTable.Arn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/oauth-callback-handler.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
      ComponentMonitoringSettings:
        - ComponentARN: !GetAtt CalendarEventsNotifier.Arn
          Tier: CUSTOM
          ComponentConfigurationMode: CUSTOM
          CustomComponentConfiguration:
            ConfigurationDetails:
              AlarmMetrics:
                - AlarmMetricName: Errors
                - AlarmMetricName: Duration
        - ComponentARN: !GetAtt WebhookFunction.Arn
          Tier: CUSTOM
          ComponentConfigurationMode: CUSTOM
          CustomComponentConfiguration:
            ConfigurationDetails:
              AlarmMetrics:
                - AlarmMetricName: Errors
                - AlarmMetricName: Duration
        - ComponentARN: !GetAtt OAuthCallbackFunction.Arn
          Tier: CUSTOM
          ComponentConfigurationMode: CUSTOM
          CustomComponentConfiguration:
            ConfigurationDetails:
              AlarmMetrics:
                - AlarmMetricName: Errors
                - AlarmMetricName: Duration
        - ComponentARN: !GetAtt OAuthStateTable.Arn
          Tier: CUSTOM
          ComponentConfigurationMode: CUSTOM
          CustomComponentConfiguration:
            ConfigurationDetails:
              AlarmMetrics:
                - AlarmMetricName: SystemErrors
        - ComponentARN: !GetAtt OAuthTokensTable.Arn
          Tier: CUSTOM
          ComponentConfigurationMode: CUSTOM
          CustomComponentConfiguration:
            ConfigurationDetails:
              AlarmMetrics:
                - AlarmMetricName: SystemErrors
  # OAuth stateパラメータを管理するDynamoDBテーブル
  # stateパラメータを一時的に保存し、TTLで自動的に削除される
  OAuthStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-oauth-state
      # 使用量に応じた課金モード
      BillingMode: PAY_PER_REQUEST
      # パーティションキーとしてstateを使用
      AttributeDefinitions:
        - AttributeName: state
          AttributeType: S
      KeySchema:
        - AttributeName: state
          KeyType: HASH
      # TTLを有効化し、一定時間後に自動的に削除
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # OAuthトークンを管理するDynamoDBテーブル
  # ユーザーごとのアクセストークンとリフレッシュトークンを保存
  # Googleのリフレッシュトークンは有効期限がないため、TTLを使用しない
  OAuthTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-oauth-tokens
      # 使用量に応じた課金モード
      BillingMode: PAY_PER_REQUEST
      # パーティションキーとしてuserIdを使用
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  # ユーザーカレンダー購読情報を管理するDynamoDBテーブル
  # ユーザーごとの購読カレンダー情報を保存
  UserCalendarsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-UserCalendars
      # 使用量に応じた課金モード
      BillingMode: PAY_PER_REQUEST
      # パーティションキーとしてuserIdを使用、ソートキーとしてcalendarIdを使用
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: calendarId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: calendarId
          KeyType: RANGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhookApi:
    Description: API Gateway endpoint URL for Prod stage for Webhook function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  OAuthCallbackApi:
    Description: API Gateway endpoint URL for Prod stage for OAuth callback function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/oauth/callback/"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        STACK_NAME: !Ref AWS::StackName
        USER_CALENDARS_TABLE: !Ref UserCalendarsTable
