name: Test

on:
  pull_request:

jobs:
  exec-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".tool-versions"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test
        # 失敗しても次のステップを実行する
        continue-on-error: true

      - name: Run only parameter-fetcher test
        run: bun run test __tests__/lib/parameter-fetcher.test.ts
