name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  exec-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".tool-versions"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests (with lcov coverage)
        run: bun run test

      - name: Run octocov
        uses: k1LoW/octocov-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save markdown coverage summary
        if: always()
        run: |
          mkdir -p docs/development
          if [ -n "${GITHUB_STEP_SUMMARY}" ] && [ -f "${GITHUB_STEP_SUMMARY}" ]; then
            cp "${GITHUB_STEP_SUMMARY}" docs/development/coverage_latest.md
          else
            echo "(No summary available)" > docs/development/coverage_latest.md
          fi
