name: Type Check

on:
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".tool-versions"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type check
        run: bunx tsc --noEmit